import type { Metadata } from "next"
import dynamic from "next/dynamic"
import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"
import FooterSection from "../components/sections/FooterSection"
import ParallaxWrapper from "../components/ParallaxWrapper"

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
})

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
})

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

const CrispWithNoSSR = dynamic(() => import("../components/ui/crisp"))

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<CrispWithNoSSR />
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<ParallaxWrapper>
					{children}
					<FooterSection />
				</ParallaxWrapper>
			</body>
		</html>
	)
}
